### ISSUE TITLE
Make a Team account

### ISSUE THREAD

**Issue by mattwynne** [nelson-social/community#1]
And mention in the bio who the admins/mods are.

Forward team email to all 3.

**Comment by tillkruss** [comment]
@blaine @mattwynne: What should the @handle be of the "team" account? We can't change the name in the future.

**Comment by blaine** [comment]
> @blaine @mattwynne: What should the @handle be of the "team" account? We can't change the name in the future.

Why not?

I'd start with admin@ just because that's a common convention, but not fussed either way.

**Comment by mattwynne** [comment]
+1 for admin or maybe admins?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tillkruss** [comment]
@mattwynne: I don't think Mastodon will let me rename users.

**Comment by tillkruss** [comment]
Done!

<img width="598" alt="Screenshot 2022-12-10 at 8 44 28 AM" src="https://user-images.githubusercontent.com/665029/206865791-c445506f-343d-4d98-a5fc-de677bda8628.png">

<img width="244" alt="Screenshot 2022-12-10 at 8 44 37 AM" src="https://user-images.githubusercontent.com/665029/206865801-75c88398-aa1a-49d3-9ab0-e7c905ae3e7b.png">

**Comment by mattwynne** [comment]
Nice one!Can you share the login details with me and @blaine? Maybe you already did and I missed the memo?

**Comment by mattwynne** [comment]
Well, I was thinking that it would allow us to:

1. Fiddle about with the server rules settings etc. and tweak the about page copy.
2. See when we get DMs or mentions to that account so it doesn't all fall to you.

**Comment by tillkruss** [comment]
I don't want a shared admin account (too much ambiguity), I can promote your `@matt` account to admin, tho? And use the `@admin` just for DMs.

>Fiddle about with the server rules settings etc. and tweak the about page copy.

Can you keep a log of what settings you change?

**Comment by tillkruss** [comment]
- `matt` is now an admin
- `admin` is now a regular user

**Comment by mattwynne** [comment]
OK that works, thanks!

> Can you keep a log of what settings you change?

👍

My only question now is what we should say to people about how to contact "us" if they have a question or moderation complaint or whatever. Should we tell them to DM this @admin account? Send an email to admin@nelson.social? I just want to make sure that if someone does contact us, we'll get the message!

**Comment by tillkruss** [comment]
I guess the email works? We could use follow-requests, so people can't just DM the `admin` account, but still see the bio with our names and email.

**Comment by mattwynne** [comment]
OK, I've used the email in the copy for #16.

What are "follow-requests"?

**Comment by tillkruss** [comment]
I have not used these. It would certainly prevent from us not seeing DMs in the admin account.

<img width="503" alt="Screenshot 2022-12-15 at 10 16 41 AM" src="https://user-images.githubusercontent.com/665029/207936956-4b08103c-32bb-41c9-a7bf-fa5d1d3d324c.png">

**Comment by tillkruss** [comment]
Or maybe we make a pinned post on that account with instructions on how to contact us.

Annoying that you must-have an "owner" and that's a single account.
