### ISSUE TITLE
Welcome protocol

### ISSUE THREAD

**Issue by mattwynne** [nelson-social/community#2]
We’ll socialise and introduce new members when they join. They’ll get a warm welcome on the app, as well as a welcome email with some helpful tips.

- [ ] template copy for #introduction welcome message
- [ ] template copy for welcome email
- [ ] try it out / test it!

Some things to include in the messaging:

- Introduce the person who you invited
- What did I miss CTA?
- Calendly link to schedule call?
- How do we do things?
- Vision + name + avatar
- Want to get involved?

**Comment by tillkruss** [comment]
Welcome email

- Purpose / vision of the instance, why are we doing this, what is it?
- Why not FB? What the story we’re telling?
- Who’s invited? Yes, it’s exclusive & private 
- WTF is Mastodon / Fediverse
- Actions:
  - Full names only? First name + IRL photo?
  - How to get started (links to apps) how to see local timeline
  - Review the server rules and code of conduct (link)
