### ISSUE TITLE
Server Rules

### ISSUE THREAD

**Issue by blaine** [nelson-social/community#8]
https://github.com/nelson-social/community/blob/96af4c6c80b0a7b644ad361395ed3a0e6eeb9ea6/ABOUT.md?plain=1#L23-L24

I'm not a big fan of these two lines. I think we should have a "casual but professional" tone to the rules.

I quite like [Ottawa's rules](https://ottawa.place/about/more) because they're clear an unambiguous around things that might result in individuals getting reprimanded or kicked out. @mattwynne mentioned [social.coop's rules](https://wiki.social.coop/rules-and-bylaws/Code-of-conduct.html), which I also think are great, but maybe too much to start?

I worry about the [living room rules](https://notebook.drmaciver.com/posts/2020-07-14-13:42.html) approach, because of the small nature of our community; if we do want to have a bigger umbrella, it'll be important that we're not seen as "arbitrary" or biased. If we were running nelson-gamer-nerds.club or twentysomething-ski-bums-of-nelson.pub, I think the living room rules would be totally appropriate.

**Comment by mattwynne** [comment]
This really sits under https://github.com/nelson-social/community/issues/3

**Comment by mattwynne** [comment]
My hope was that, once #1 is done, I can have a fiddle about with what Mastodon offers us in terms of content on the about/more page and try to get something that sets the right tone.

**Comment by mattwynne** [comment]
I think they go together really. I’d like to have a CoC and then summarise it with the rules. Give me a few days to get a draft?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tillkruss** [comment]
Go for it 👍
